# Generated by Django 5.0.2 on 2024-02-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accountId', models.IntegerField()),
                ('exercises', models.ManyToManyField(to='workout.exercise')),
            ],
        ),
    ]
